name: 🚀 Deploy to Netzguerilla on push
on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - '!src/**/*.test.ts'
      - 'public/**'
      - 'vendor/**'
      - 'package*.json'
      - 'astro.config.*'
      - 'tsconfig.json'
  workflow_dispatch:

jobs:
  web-deploy:
    name: Build & Deploy with encrypted private key
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v6

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: 🔨 Build Project
        run: |
          npm ci
          npm run build

      - name: 🕐 Update deploy stamp
        run: echo "$(date -u +%s)" > deploy.stamp

      - name: 📤 Deploy /dist
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          username: ${{ secrets.FTP_USERNAME }}
          server: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          local_path: "./dist/*"
          remote_path: "/home/sebastian/websites/fairshare.syndikit.de/dist"
          sftp_only: true
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_passphrase: ${{ secrets.SSH_PASSPHRASE }}

      - name: 📤 Deploy package.json
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          username: ${{ secrets.FTP_USERNAME }}
          server: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          local_path: "./package*.json"
          remote_path: "/home/sebastian/websites/fairshare.syndikit.de"
          sftp_only: true
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_passphrase: ${{ secrets.SSH_PASSPHRASE }}

      - name: 📤 Deploy deploy.stamp  # ← zuletzt!
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          username: ${{ secrets.FTP_USERNAME }}
          server: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          local_path: "./deploy.stamp"
          remote_path: "/home/sebastian/websites/fairshare.syndikit.de"
          sftp_only: true
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_passphrase: ${{ secrets.SSH_PASSPHRASE }}          